# Your Name or Company
title: Lee ju hyeong

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: I want to become a server developer.
  So I develop a medical service app to help the needy and poor.
  We want to provide equal access to better information and better services.
  Furthermore, I want to help people whose lives are difficult.

# Add your social links
social:
  - platform: github
    url: https://github.com/isyouhyeong
  - platform: instagram
    url: https://www.instagram.com/isyouh/
  - platform: Notion
    url: https://fern-sun-8b5.notion.site/d829e3df8d6c47ab850687011e101e28
  - platform: velog
    url: https://velog.io/@isyouh77/posts

# General settings
url: "https://isyouhyeong.github.io"
# baseurl: "/uni"
markdown: kramdown
sharing_image: "bluepicture.jpg"
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: left

# Full layout
full_text_position: left # left, right or center
