# Your Name or Company
title: Lee ju hyeong

# Description of your website. This is used for social sharing.
description:  The beautiful website of artist, poet, craftsperson, cyclist, and avid juggler, Uni Kravitz.

# A brief blurb about yourself
content: I want to become a server developer in Korea.
To the difficult and poor,
Better information and better services equally
I'd like to offer it.

# Add your social links
social:
  - platform: github
    url: https://github.com/isyouhyeong
  - platform: instagram
    url: https://www.instagram.com/isyouh/
  - platform: Notion
    url: https://www.notion.so/9ea26b9d7f08487daf515f33b9bce4cf
  - platform: velog
    url: https://velog.io/@isyouh77/posts

# General settings
# url: "https://isyouhyeong.github.io/"
# baseurl: "" 
markdown: kramdown
sharing_image: black.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
